name: Build FioCaixa APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permissão Gradle
        run: chmod +x gradlew

      - name: Compilar APK
        run: ./gradlew assembleDebug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: FioCaixa-debug
          path: app/build/outputs/apk/debug/*.apk
