name: Build Android APK

on:
  push:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch: # Permite que você inicie a compilação manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permissão ao Gradle
      run: chmod +x gradlew

    - name: Compilar o APK em modo Debug
      run: ./gradlew assembleDebug

    - name: Disponibilizar o APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: App-FioCaixa
        path: '**/*.apk'
